services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/engine
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=159753
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: engine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d engine -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
