package com.ecommerce.engine.exception.handler;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    INTERNAL_ERROR,
    NULL_POINTER,
    JSON_PARSE_ERROR,
    SEARCH_FIELD_NOT_FOUND,
    INVALID_SEARCH_REQUEST,
    EMAIL_ALREADY_USED,
    PASSWORD_IS_NOT_SAFE,
    INTEGRITY_VIOLATION,
    RECORD_HAS_USAGES,
    BAD_SQL_GRAMMAR,
    NOT_UNIQUE,
    DEFAULT_ENTITY,
    CANNOT_ENABLE,
    INVALID_CONFIGURATION,
    NOT_ALLOWED_FILTER
}
