package com.ecommerce.engine.exception.handler;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    INTERNAL_ERROR,
    NULL_POINTER,
    JSON_PARSE_ERROR,
    EMAIL_ALREADY_USED,
    PASSWORD_IS_NOT_SAFE,
    RECORD_HAS_USAGES,
    BAD_SQL_GRAMMAR,
    NOT_UNIQUE,
    DEFAULT_ENTITY,
    INVALID_CONFIGURATION,
}
