name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master  # Adjust this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build  # Ensure your Gradle wrapper is set up

      - name: Find the latest JAR file
        id: jar_file
        run: |
          echo "Finding JAR file..."
          JAR_FILE=$(ls build/libs/*.jar | sort -V | tail -n 1)
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV

      - name: Copy JAR file to Droplet
        env:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          echo "$DROPLET_SSH_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ${{ env.JAR_FILE }} $DROPLET_USER@$DROPLET_IP:/opt/cms-engine/
          rm private_key

      - name: Deploy application
        env:
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP << 'EOF'
            cd /opt/cms-engine
            java -jar $(basename ${{ env.JAR_FILE }}) > app.log 2>&1 &
          EOF
