name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: Package

      - name: Debug List downloaded artifacts
        run: ls -la

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}

          script: |
            # Check if the JAR file exists in the current directory
            echo "Current Directory Contents:"
            ls -la
            
            # Copy the JAR file to the droplet
            mkdir -p /opt/cms-engine/
            # Ensure the correct file name is referenced
            if [ -f cms-engine-0.0.1-SNAPSHOT.jar ]; then
              rsync -avz --progress cms-engine-0.0.1-SNAPSHOT.jar /opt/cms-engine/
            else
              echo "JAR file does not exist in the current directory!"
              exit 1
            fi
            
            # Check if the JAR file exists on the droplet before starting
            if [ -f /opt/cms-engine/cms-engine-0.0.1-SNAPSHOT.jar ]; then
              # Stop the old app and start the new one
              pkill -f 'java -jar' || true
              nohup java -jar /opt/cms-engine/cms-engine-0.0.1-SNAPSHOT.jar > /opt/cms-engine/app.log 2>&1 &
            else
              echo "JAR file does not exist on the droplet!"
              exit 1
            fi

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
